# Docker Compose Configuration for Production
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: "3.8"

services:
  githound-web:
    build:
      target: production
    environment:
      - GITHOUND_ENV=production
      - GITHOUND_DEBUG=false
      - GITHOUND_LOG_LEVEL=warning
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    command:
      [
        "uvicorn",
        "githound.web.api:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--workers",
        "4",
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  githound-mcp:
    build:
      target: production
    environment:
      - GITHOUND_ENV=production
      - GITHOUND_DEBUG=false
      - GITHOUND_LOG_LEVEL=warning
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  nginx:
    profiles: [] # Enable nginx in production
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
